name: MasterCI

on:
  push:
    branches:
      - master
# on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: cd stable/debian && docker build .